env:
  browser: true
  node: true
  es6: true
extends: 'eslint:recommended'
parserOptions:
  sourceType: module
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - never
  prefer-const:
    - error
    - destructuring: any
  no-var:
    - error
  brace-style:
    - error
    - stroustrup
  curly:
    - error
    - multi-line
  keyword-spacing:
    - error
