env:
  browser: true
  node: true
  es6: true
extends: 'eslint:recommended'
parserOptions:
  sourceType: module
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - never
  prefer-const:
    - error
    - destructuring: any
  no-var:
    - error
  brace-style:
    - error
    - stroustrup
  curly:
    - error
    - multi-line
  keyword-spacing:
    - error
  one-var:
    - error
    - never
  prefer-arrow-callback:
    - error
  newline-per-chained-call:
    - error
    - ignoreChainWithDepth: 1
  space-before-function-paren:
    - error
    - always
